/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javax.swing.SwingUtilities;

public class Main {
    public static void main(String[] args) {
      SwingUtilities.invokeLater(new Runnable() {
        public void run() {
          new WormWindow();
        }
      });
    }
}
