/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import graphics.WormWindow;

public class Main {
    public static void main(String[] args) {
        new WormWindow();
    }
}
